Dblogin            = "USER:PASSWORD@/blog_cannon"
Guestmode          = true
AdminPWD           = "cannon"
Templatefolder     = "/home/user/blog_cannon/template"
BlogName           = "blog_cannon"
CoinHiveToken      = "Y4dhjhwB3ssbl897BQzY4iq1B1rPVOOK"
TrackTrackGo       = "https://UrlToTrackTrackGo"
JabberNotification = true
JabberHost         = "example.com:5222"
JabberUser         = "user@example.com"
JabberPassword     = "password"
JabberServerName   = "ejabberd"
JabberJIDreciever  = "reciever@example.com"
JabberInsecureSkipVerify = true
